# Generate a Windows module-definition (.def) file that exports the qvac-fabric
# runtime surface (llama / ggml / common / mtmd) from the static libraries that
# are linked into qvac__fabric.bare. This mirrors the symbol allow-list applied
# by symbols.map (ELF version script) and exports.txt (Mach-O exported list) so
# consumer addons resolve the same llama/ggml/common API against the single
# shared runtime on every platform.
#
# Listing a symbol under EXPORTS acts as a reference, so the linker pulls the
# defining member out of the (non-whole-archived) static libraries on demand.
# Because the export list is generated by scanning those exact archives, every
# listed symbol is guaranteed to be present in the image, which avoids both the
# "unresolved export" errors of a hand-written .def and the duplicate-symbol
# risk of force-including whole archives.
#
# Invoked at build time:
#   cmake -DNM=<llvm-nm> -DOUTPUT=<def> "-DINPUTS=<lib>|<lib>|..." \
#         -P generate-windows-def.cmake

if(NOT NM)
  message(FATAL_ERROR "generate-windows-def.cmake: -DNM=<llvm-nm> is required")
endif()
if(NOT OUTPUT)
  message(FATAL_ERROR "generate-windows-def.cmake: -DOUTPUT=<def> is required")
endif()

# Inputs are passed pipe-separated because a Windows path never contains '|',
# whereas ';' would be re-split into separate command arguments.
string(REPLACE "|" ";" _inputs "${INPUTS}")

# Source-level name prefixes to export. Keep in sync with symbols.map.
set(_allow
  "llama_" "llava_" "mtmd_" "LLAMA_" "ggml_" "gguf_"
  "common_" "json_schema_to_grammar" "string_"
  "set_process_priority" "postprocess_cpu_params" "metadata_handle_deleter")
string(JOIN "|" _alt ${_allow})

# Match the linker symbol name. C symbols are bare ("llama_decode"); MSVC
# decorates C++ globals as "?name@@..." where the bare identifier follows the
# leading '?', so anchoring at "^_?[?]?<prefix>" matches free functions and
# data while excluding class members (e.g. std::string_view::*). This mirrors
# the version-script semantics, which match global symbols by source name.
set(_pattern "^_?[?]?(${_alt})")

set(_body "")
set(_seen "")

foreach(_input IN LISTS _inputs)
  if(NOT EXISTS "${_input}")
    continue()
  endif()

  execute_process(
    COMMAND "${NM}" --defined-only --extern-only --no-sort "${_input}"
    OUTPUT_VARIABLE _out
    RESULT_VARIABLE _rc)
  if(NOT _rc EQUAL 0)
    message(FATAL_ERROR "generate-windows-def.cmake: nm failed on ${_input} (${_rc})")
  endif()

  string(REPLACE "\r" "" _out "${_out}")
  string(REPLACE "\n" ";" _lines "${_out}")
  foreach(_line IN LISTS _lines)
    # nm lines are "<address> <type> <name>"; skip archive headers / blanks.
    if(NOT _line MATCHES "^[0-9A-Fa-f]+ ([A-Za-z]) (.+)$")
      continue()
    endif()
    set(_type "${CMAKE_MATCH_1}")
    set(_name "${CMAKE_MATCH_2}")

    if(NOT _name MATCHES "${_pattern}")
      continue()
    endif()
    if(_name IN_LIST _seen)
      continue()
    endif()
    list(APPEND _seen "${_name}")

    # Code symbols are T/t (text) and W/w (weak, e.g. C++ template instances);
    # everything else (D/R/B/V/...) is data and must carry the DATA keyword so
    # consumers reference it through the correct relocation.
    if(_type MATCHES "[TtWw]")
      string(APPEND _body "    ${_name}\n")
    else()
      string(APPEND _body "    ${_name} DATA\n")
    endif()
  endforeach()
endforeach()

file(WRITE "${OUTPUT}" "EXPORTS\n${_body}")
