#include "StepDoctrRecognitionGGML.hpp"

#include <algorithm>
#include <array>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <limits>
#include <memory>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

#include <ggml-alloc.h>
#include <ggml-backend.h>
#include <ggml-cpu.h>
#include <ggml.h>
#include <gguf.h>
#include <opencv2/opencv.hpp>

#include "model-interface/easyocr/pipeline/qlog.hpp"

// NOLINTBEGIN(cppcoreguidelines-pro-bounds-pointer-arithmetic,cppcoreguidelines-pro-bounds-constant-array-index,readability-identifier-naming,readability-identifier-length)
// DSP / LSTM / CRNN inner loops use raw pointer arithmetic, single-letter
// math identifiers (x, t, c, h, bn), snake_case to mirror upstream PyTorch
// state-dict paths, and layer-dim magic numbers that are themselves part
// of the model architecture. Bounds-checking, renaming, or "constant-ising"
// these would either change the source diff against upstream or measurably
// regress hot-path CTC decode / LSTM gate compute throughput.

namespace doctr::ggml::pipeline {

// NOLINTNEXTLINE(bugprone-throwing-static-initialization)
const std::string StepDoctrRecognitionGGML::VOCAB =
    "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
    "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~"
    "\xC2\xB0"
    "\xC2\xA3"
    "\xE2\x82\xAC"
    "\xC2\xA5"
    "\xC2\xA2"
    "\xE0\xB8\xBF"
    "\xC3\xA0"
    "\xC3\xA2"
    "\xC3\xA9"
    "\xC3\xA8"
    "\xC3\xAA"
    "\xC3\xAB"
    "\xC3\xAE"
    "\xC3\xAF"
    "\xC3\xB4"
    "\xC3\xB9"
    "\xC3\xBB"
    "\xC3\xBC"
    "\xC3\xA7"
    "\xC3\x80"
    "\xC3\x82"
    "\xC3\x89"
    "\xC3\x88"
    "\xC3\x8A"
    "\xC3\x8B"
    "\xC3\x8E"
    "\xC3\x8F"
    "\xC3\x94"
    "\xC3\x99"
    "\xC3\x9B"
    "\xC3\x9C"
    "\xC3\x87";

namespace {

constexpr int kInputChannels = 3;
constexpr int kFeatureChannels = 576;
constexpr int kSequenceLength = 32;
constexpr int kVocabSize = 127;
constexpr int kLstmHiddenSize = 128;
constexpr int kLstmLayerCount = 2;
constexpr int kLstmDirectionCount = 2;
constexpr int kLstmGateCount = 4;
constexpr double kPixelMax = 255.0;

// Sizing constants for the three ggml contexts the recognizer allocates.
// `kWeightsCtxTensorOverhead` is the number of tensor headers we reserve for
// uploading the recognizer weight set; `kGraphCtxTensorOverhead` covers the
// nodes generated by `build_crnn_gen2`; `kMaxGraphNodes` is the upper bound
// passed to `ggml_new_graph_custom`. All are deliberately oversized; the
// real model footprint stays well below them.
constexpr int kGraphCtxTensorOverhead = 4096;
constexpr int kMaxGraphNodes = 8192;

// NOLINTBEGIN(bugprone-throwing-static-initialization)
// NOLINTNEXTLINE(modernize-use-std-numbers) - dataset-derived RGB normalization
const cv::Scalar DOCTR_RECO_MEAN(0.694, 0.695, 0.693);
const cv::Scalar DOCTR_RECO_STD(0.299, 0.296, 0.301);
// NOLINTEND(bugprone-throwing-static-initialization)

struct BlockConfig {
  int featureIndex;
  int inputChannels;
  int outputChannels;
  int expansionChannels;
  int kernel;
  bool useSe;
  bool useHardswish;
  int strideW;
  int strideH;
};

constexpr std::array<BlockConfig, 11> kBlocks{{
    {.featureIndex = 1,
     .inputChannels = 16,
     .outputChannels = 16,
     .expansionChannels = 16,
     .kernel = 3,
     .useSe = true,
     .useHardswish = false,
     .strideW = 2,
     .strideH = 2},
    {.featureIndex = 2,
     .inputChannels = 16,
     .outputChannels = 24,
     .expansionChannels = 72,
     .kernel = 3,
     .useSe = false,
     .useHardswish = false,
     .strideW = 1,
     .strideH = 2},
    {.featureIndex = 3,
     .inputChannels = 24,
     .outputChannels = 24,
     .expansionChannels = 88,
     .kernel = 3,
     .useSe = false,
     .useHardswish = false,
     .strideW = 1,
     .strideH = 1},
    {.featureIndex = 4,
     .inputChannels = 24,
     .outputChannels = 40,
     .expansionChannels = 96,
     .kernel = 5,
     .useSe = true,
     .useHardswish = true,
     .strideW = 1,
     .strideH = 2},
    {.featureIndex = 5,
     .inputChannels = 40,
     .outputChannels = 40,
     .expansionChannels = 240,
     .kernel = 5,
     .useSe = true,
     .useHardswish = true,
     .strideW = 1,
     .strideH = 1},
    {.featureIndex = 6,
     .inputChannels = 40,
     .outputChannels = 40,
     .expansionChannels = 240,
     .kernel = 5,
     .useSe = true,
     .useHardswish = true,
     .strideW = 1,
     .strideH = 1},
    {.featureIndex = 7,
     .inputChannels = 40,
     .outputChannels = 48,
     .expansionChannels = 120,
     .kernel = 5,
     .useSe = true,
     .useHardswish = true,
     .strideW = 1,
     .strideH = 1},
    {.featureIndex = 8,
     .inputChannels = 48,
     .outputChannels = 48,
     .expansionChannels = 144,
     .kernel = 5,
     .useSe = true,
     .useHardswish = true,
     .strideW = 1,
     .strideH = 1},
    {.featureIndex = 9,
     .inputChannels = 48,
     .outputChannels = 96,
     .expansionChannels = 288,
     .kernel = 5,
     .useSe = true,
     .useHardswish = true,
     .strideW = 1,
     .strideH = 2},
    {.featureIndex = 10,
     .inputChannels = 96,
     .outputChannels = 96,
     .expansionChannels = 576,
     .kernel = 5,
     .useSe = true,
     .useHardswish = true,
     .strideW = 1,
     .strideH = 1},
    {.featureIndex = 11,
     .inputChannels = 96,
     .outputChannels = 96,
     .expansionChannels = 576,
     .kernel = 5,
     .useSe = true,
     .useHardswish = true,
     .strideW = 1,
     .strideH = 1},
}};

// UTF-8 lead-byte masks for parseVocabToChars: a UTF-8 leading byte
// determines the length of the encoded code point by the position of the
// first 0 bit. See https://en.wikipedia.org/wiki/UTF-8#Encoding for the bit
// patterns. These masks isolate that prefix so the test `(c & mask) == val`
// classifies the byte.
constexpr unsigned char kUtf8OneByteMask = 0x80;    // 1000 0000
constexpr unsigned char kUtf8TwoByteMask = 0xE0;    // 1110 0000
constexpr unsigned char kUtf8TwoByteValue = 0xC0;   // 1100 0000
constexpr unsigned char kUtf8ThreeByteMask = 0xF0;  // 1111 0000
constexpr unsigned char kUtf8ThreeByteValue = 0xE0; // 1110 0000
constexpr unsigned char kUtf8FourByteMask = 0xF8;   // 1111 1000
constexpr unsigned char kUtf8FourByteValue = 0xF0;  // 1111 0000

std::vector<std::string> parseVocabToChars(const std::string& vocab) {
  std::vector<std::string> chars;
  size_t i = 0;
  while (i < vocab.size()) {
    int len = 1;
    const auto c = static_cast<unsigned char>(vocab[i]);
    if ((c & kUtf8OneByteMask) == 0) {
      len = 1;
    } else if ((c & kUtf8TwoByteMask) == kUtf8TwoByteValue) {
      len = 2;
    } else if ((c & kUtf8ThreeByteMask) == kUtf8ThreeByteValue) {
      len = 3;
    } else if ((c & kUtf8FourByteMask) == kUtf8FourByteValue) {
      len = 4;
    }
    chars.push_back(vocab.substr(i, static_cast<size_t>(len)));
    i += static_cast<size_t>(len);
  }
  return chars;
}

[[noreturn]] void raise(const std::string& message) {
  throw std::runtime_error("[DoctrRecognitionGGML] " + message);
}

void fp16ToFp32(const void* src, float* out, size_t count) {
  const auto* halfPtr = static_cast<const ggml_fp16_t*>(src);
  for (size_t i = 0; i < count; ++i) {
    out[i] = ggml_fp16_to_fp32(halfPtr[i]);
  }
}

int samePadding(int kernel) { return (kernel - 1) / 2; }

float sigmoid(float value) { return 1.0F / (1.0F + std::exp(-value)); }

struct LstmWeights {
  std::vector<float> weightIh;
  std::vector<float> weightHh;
  std::vector<float> biasIh;
  std::vector<float> biasHh;
  int inputSize{};
};

struct GraphResources {
  std::unique_ptr<struct ggml_context, decltype(&ggml_free)> weightsCtx{
      nullptr, ggml_free};
  std::unique_ptr<struct ggml_context, decltype(&ggml_free)> extraCtx{
      nullptr, ggml_free};
  std::unique_ptr<struct ggml_context, decltype(&ggml_free)> graphCtx{
      nullptr, ggml_free};
  std::unordered_map<std::string, struct ggml_tensor*> weights;
  ggml_backend_t backend = nullptr;
  ggml_backend_buffer_t weightsBuffer = nullptr;
  ggml_backend_buffer_t extraBuffer = nullptr;
  ggml_backend_buffer_t graphBuffer = nullptr;
  std::vector<ggml_backend_buffer_t> auxBuffers;
  struct ggml_cgraph* graph = nullptr;
  struct ggml_tensor* input = nullptr;
  struct ggml_tensor* features = nullptr;

  GraphResources() = default;
  ~GraphResources() { reset(); }
  GraphResources(const GraphResources&) = delete;
  GraphResources& operator=(const GraphResources&) = delete;
  GraphResources(GraphResources&&) = delete;
  GraphResources& operator=(GraphResources&&) = delete;

  void reset() {
    graph = nullptr;
    input = nullptr;
    features = nullptr;
    graphCtx.reset();
    if (graphBuffer != nullptr) {
      ggml_backend_buffer_free(graphBuffer);
      graphBuffer = nullptr;
    }
    weights.clear();
    extraCtx.reset();
    if (extraBuffer != nullptr) {
      ggml_backend_buffer_free(extraBuffer);
      extraBuffer = nullptr;
    }
    weightsCtx.reset();
    if (weightsBuffer != nullptr) {
      ggml_backend_buffer_free(weightsBuffer);
      weightsBuffer = nullptr;
    }
    for (ggml_backend_buffer_t buf : auxBuffers) {
      if (buf != nullptr) {
        ggml_backend_buffer_free(buf);
      }
    }
    auxBuffers.clear();
    if (backend != nullptr) {
      ggml_backend_free(backend);
      backend = nullptr;
    }
  }
};

struct GraphBuilder {
  struct ggml_context* ctx;
  // GraphBuilder is a stateless one-shot helper that never outlives its
  // caller; storing the weight map by reference avoids a deep copy on every
  // graph build.
  // NOLINTNEXTLINE(cppcoreguidelines-avoid-const-or-ref-data-members)
  const std::unordered_map<std::string, struct ggml_tensor*>& w;

  [[nodiscard]] struct ggml_tensor* t(const std::string& name) const {
    auto it = w.find(name);
    if (it == w.end()) {
      raise("missing graph tensor: " + name);
    }
    return it->second;
  }

  struct ggml_tensor* activate(struct ggml_tensor* x, bool useHardswish) const {
    return useHardswish ? ggml_hardswish(ctx, x) : ggml_relu(ctx, x);
  }

  void requireMatchingConvDtypes(
      const struct ggml_tensor* kernelT, const struct ggml_tensor* input,
      const char* opLabel) const {
    if (kernelT->type == input->type) {
      return;
    }
    raise(
        std::string("Conv dtype mismatch at ") + opLabel + ": kernel " +
        kernelT->name + " is " + ggml_type_name(kernelT->type) +
        " but input is " + ggml_type_name(input->type) +
        " — KleidiAI dispatch requires matching dtypes.");
  }

  struct ggml_tensor* convBnAct(
      struct ggml_tensor* x,
      // NOLINTNEXTLINE(bugprone-easily-swappable-parameters)
      const std::string& convPrefix, int strideW,
      int strideH, int kernel, bool applyActivation, bool useHardswish) const {
    struct ggml_tensor* kernelT = t(convPrefix + ".weight");
    requireMatchingConvDtypes(kernelT, x, "ggml_conv_2d_direct");
    struct ggml_tensor* conv = ggml_conv_2d_direct(
        ctx,
        kernelT,
        x,
        strideW,
        strideH,
        samePadding(kernel),
        samePadding(kernel),
        1,
        1);
    conv = ggml_add(ctx, conv, t(convPrefix + ".bias_br"));
    return applyActivation ? activate(conv, useHardswish) : conv;
  }

  struct ggml_tensor* dwConvBnAct(
      struct ggml_tensor* x,
      // NOLINTNEXTLINE(bugprone-easily-swappable-parameters)
      const std::string& convPrefix, int strideW,
      int strideH, int kernel, bool useHardswish) const {
    struct ggml_tensor* kernelT = t(convPrefix + ".weight");
    requireMatchingConvDtypes(kernelT, x, "ggml_conv_2d_dw_direct");
    struct ggml_tensor* conv = ggml_conv_2d_dw_direct(
        ctx,
        kernelT,
        x,
        strideW,
        strideH,
        samePadding(kernel),
        samePadding(kernel),
        1,
        1);
    conv = ggml_add(ctx, conv, t(convPrefix + ".bias_br"));
    return activate(conv, useHardswish);
  }

  struct ggml_tensor* convBiasAct(
      struct ggml_tensor* x, const std::string& convPrefix,
      bool applyActivation, bool useHardswish) const {
    struct ggml_tensor* kernelT = t(convPrefix + ".weight");
    requireMatchingConvDtypes(kernelT, x, "ggml_conv_2d_direct");
    struct ggml_tensor* conv =
        ggml_conv_2d_direct(ctx, kernelT, x, 1, 1, 0, 0, 1, 1);
    conv = ggml_add(ctx, conv, t(convPrefix + ".bias_br"));
    return applyActivation ? activate(conv, useHardswish) : conv;
  }

  struct ggml_tensor*
  seBlock(struct ggml_tensor* x, const std::string& sePrefix) const {
    struct ggml_tensor* pooled = ggml_pool_2d(
        ctx,
        x,
        GGML_OP_POOL_AVG,
        static_cast<int>(x->ne[0]),
        static_cast<int>(x->ne[1]),
        static_cast<int>(x->ne[0]),
        static_cast<int>(x->ne[1]),
        0,
        0);
    struct ggml_tensor* fc1 =
        convBiasAct(pooled, sePrefix + ".fc1", true, false);
    struct ggml_tensor* fc2 = convBiasAct(fc1, sePrefix + ".fc2", false, false);
    return ggml_mul(ctx, x, ggml_hardsigmoid(ctx, fc2));
  }

  struct ggml_tensor*
  invertedResidual(struct ggml_tensor* x, const BlockConfig& cfg) const {
    const std::string base =
        "crnn.features." + std::to_string(cfg.featureIndex);
    const bool hasExpand = cfg.expansionChannels != cfg.inputChannels;
    int dwBlockIdx = 0;
    int seBlockIdx = -1;
    int projBlockIdx = 0;

    struct ggml_tensor* y = x;
    if (hasExpand) {
      y = convBnAct(
          y,
          base + ".block.0.0",
          1,
          1,
          1,
          true,
          cfg.useHardswish);
      dwBlockIdx = 1;
      if (cfg.useSe) {
        seBlockIdx = 2;
        projBlockIdx = 3;
      } else {
        projBlockIdx = 2;
      }
    } else if (cfg.useSe) {
      seBlockIdx = 1;
      projBlockIdx = 2;
    } else {
      projBlockIdx = 1;
    }

    const std::string dwBase = base + ".block." + std::to_string(dwBlockIdx);
    y = dwConvBnAct(
        y,
        dwBase + ".0",
        cfg.strideW,
        cfg.strideH,
        cfg.kernel,
        cfg.useHardswish);

    if (cfg.useSe) {
      y = seBlock(y, base + ".block." + std::to_string(seBlockIdx));
    }

    const std::string projBase =
        base + ".block." + std::to_string(projBlockIdx);
    y = convBnAct(
        y, projBase + ".0", 1, 1, 1, false, cfg.useHardswish);

    if (cfg.strideW == 1 && cfg.strideH == 1 &&
        cfg.inputChannels == cfg.outputChannels) {
      y = ggml_add(ctx, y, x);
    }
    return y;
  }
};

} // namespace

struct StepDoctrRecognitionGGML::Impl {
  GraphResources graph;
  std::array<std::array<LstmWeights, kLstmDirectionCount>, kLstmLayerCount>
      lstm{};
  std::vector<float> linearWeight;
  std::vector<float> linearBias;

  explicit Impl(const std::string& pathRecognizer) { load(pathRecognizer); }

  void load(const std::string& pathRecognizer) {
    graph.reset();
    ggml_backend_dev_t cpuDev =
        ggml_backend_dev_by_type(GGML_BACKEND_DEVICE_TYPE_CPU);
    graph.backend = cpuDev ? ggml_backend_dev_init(cpuDev, nullptr) : nullptr;
    if (graph.backend == nullptr) {
      raise("failed to initialize ggml CPU backend");
    }

    struct ggml_context* ggufGgmlCtx = nullptr;
    gguf_init_params params{.no_alloc = true, .ctx = &ggufGgmlCtx};
    gguf_context* gguf = gguf_init_from_file(pathRecognizer.c_str(), params);
    if (gguf == nullptr) {
      raise("failed to open GGUF file: " + pathRecognizer);
    }
    std::unique_ptr<gguf_context, decltype(&gguf_free)> ggufGuard(
        gguf, gguf_free);
    graph.weightsCtx =
        std::unique_ptr<struct ggml_context, decltype(&ggml_free)>(
            ggufGgmlCtx, ggml_free);

    loadGraphWeights(gguf, pathRecognizer);
    loadRecurrentWeights(gguf, pathRecognizer);
    buildGraph();
    const size_t inputElems = static_cast<size_t>(RECOG_WIDTH) *
                              static_cast<size_t>(RECOG_HEIGHT) *
                              static_cast<size_t>(kInputChannels);
    const std::vector<float> dummyInput(inputElems, 0.0F);
    ggml_backend_tensor_set(
        graph.input,
        dummyInput.data(),
        0,
        dummyInput.size() * sizeof(float));
    ggml_backend_graph_compute(graph.backend, graph.graph);
  }

  [[nodiscard]] std::vector<float>
  runFeatureExtractor(const std::vector<float>& inputWhcn) const {
    ggml_backend_tensor_set(
        graph.input, inputWhcn.data(), 0, inputWhcn.size() * sizeof(float));

    const ggml_status status =
        ggml_backend_graph_compute(graph.backend, graph.graph);
    if (status != GGML_STATUS_SUCCESS) {
      raise(
          "ggml backend graph compute failed with status " +
          std::to_string(static_cast<int>(status)));
    }

    std::vector<float> features(
        static_cast<size_t>(ggml_nelements(graph.features)));
    ggml_backend_tensor_get(
        graph.features, features.data(), 0, features.size() * sizeof(float));
    return features;
  }

  [[nodiscard]] std::vector<float>
  runLstmLinear(const std::vector<float>& featureWhcn) const {
    std::vector<float> layerInput(
        static_cast<size_t>(kSequenceLength) * kFeatureChannels);
    for (int t = 0; t < kSequenceLength; ++t) {
      for (int c = 0; c < kFeatureChannels; ++c) {
        layerInput[(static_cast<size_t>(t) * kFeatureChannels) + c] =
            featureWhcn[t + (static_cast<size_t>(kSequenceLength) * c)];
      }
    }

    std::vector<float> layerOutput;
    for (int layer = 0; layer < kLstmLayerCount; ++layer) {
      const int inputSize = (layer == 0)
                                ? kFeatureChannels
                                : kLstmHiddenSize * kLstmDirectionCount;
      layerOutput.assign(
          static_cast<size_t>(kSequenceLength) * kLstmHiddenSize *
              kLstmDirectionCount,
          0.0F);
      runLstmDirection(
          layerInput, layerOutput, lstm[layer][0], inputSize, false);
      runLstmDirection(
          layerInput, layerOutput, lstm[layer][1], inputSize, true);
      layerInput.swap(layerOutput);
    }

    std::vector<float> logits(
        static_cast<size_t>(kSequenceLength) * kVocabSize);
    constexpr int finalFeatureSize = kLstmHiddenSize * kLstmDirectionCount;
    for (int t = 0; t < kSequenceLength; ++t) {
      const float* x =
          layerInput.data() + (static_cast<size_t>(t) * finalFeatureSize);
      for (int cls = 0; cls < kVocabSize; ++cls) {
        float value = linearBias[static_cast<size_t>(cls)];
        const float* w =
            linearWeight.data() + (static_cast<size_t>(cls) * finalFeatureSize);
        for (int i = 0; i < finalFeatureSize; ++i) {
          value += w[i] * x[i];
        }
        logits[(static_cast<size_t>(t) * kVocabSize) + cls] = value;
      }
    }
    return logits;
  }

private:
  static void runLstmDirection(
      const std::vector<float>& input, std::vector<float>& output,
      const LstmWeights& weights, int inputSize, bool reverse) {
    std::vector<float> hidden(kLstmHiddenSize, 0.0F);
    std::vector<float> cell(kLstmHiddenSize, 0.0F);
    std::array<float, static_cast<size_t>(kLstmGateCount) * kLstmHiddenSize>
        gates{};

    for (int step = 0; step < kSequenceLength; ++step) {
      const int t = reverse ? (kSequenceLength - 1 - step) : step;
      const float* x = input.data() + (static_cast<size_t>(t) * inputSize);

      for (int gate = 0; gate < kLstmGateCount * kLstmHiddenSize; ++gate) {
        float value = weights.biasIh[static_cast<size_t>(gate)] +
                      weights.biasHh[static_cast<size_t>(gate)];
        const float* wIh =
            weights.weightIh.data() + (static_cast<size_t>(gate) * inputSize);
        for (int i = 0; i < inputSize; ++i) {
          value += wIh[i] * x[i];
        }
        const float* wHh = weights.weightHh.data() +
                           (static_cast<size_t>(gate) * kLstmHiddenSize);
        for (int i = 0; i < kLstmHiddenSize; ++i) {
          value += wHh[i] * hidden[static_cast<size_t>(i)];
        }
        gates[static_cast<size_t>(gate)] = value;
      }

      for (int i = 0; i < kLstmHiddenSize; ++i) {
        const float inputGate = sigmoid(gates[static_cast<size_t>(i)]);
        const float forgetGate =
            sigmoid(gates[kLstmHiddenSize + static_cast<size_t>(i)]);
        const float cellGate =
            std::tanh(gates[(static_cast<size_t>(2) * kLstmHiddenSize) + i]);
        const float outputGate =
            sigmoid(gates[(static_cast<size_t>(3) * kLstmHiddenSize) + i]);
        cell[static_cast<size_t>(i)] =
            (forgetGate * cell[static_cast<size_t>(i)]) +
            (inputGate * cellGate);
        hidden[static_cast<size_t>(i)] =
            outputGate * std::tanh(cell[static_cast<size_t>(i)]);
      }

      const int directionOffset = reverse ? kLstmHiddenSize : 0;
      float* out =
          output.data() +
          static_cast<size_t>(
              (t * kLstmHiddenSize * kLstmDirectionCount) + directionOffset);
      std::memcpy(out, hidden.data(), kLstmHiddenSize * sizeof(float));
    }
  }

  // NOLINTNEXTLINE(readability-function-cognitive-complexity)
  void loadGraphWeights(
      gguf_context* gguf, const std::string& ggufPath) {
    struct ggml_context* ctx = graph.weightsCtx.get();

    constexpr size_t kBiasBrHeaderBudget = 256;
    graph.extraCtx =
        std::unique_ptr<struct ggml_context, decltype(&ggml_free)>(
            ggml_init({.mem_size =
                           kBiasBrHeaderBudget * ggml_tensor_overhead(),
                       .mem_buffer = nullptr,
                       .no_alloc = true}),
            ggml_free);
    if (!graph.extraCtx) {
      raise("failed to allocate extra ggml context for bias_br tensors");
    }
    struct ggml_context* extraCtx = graph.extraCtx.get();

    auto registerConvWeight = [&](const std::string& name) {
      struct ggml_tensor* t = ggml_get_tensor(ctx, name.c_str());
      if (t == nullptr) {
        raise("missing GGUF tensor: " + name);
      }
      graph.weights.emplace(name, t);
      return t;
    };

    auto addBiasBroadcast =
        [&](const std::string& biasName, int64_t channels) {
          const std::string brName = biasName + "_br";
          if (graph.weights.contains(brName)) {
            return;
          }
          const std::array<int64_t, 4> shape4d = {1, 1, channels, 1};
          struct ggml_tensor* t =
              ggml_new_tensor(extraCtx, GGML_TYPE_F32, 4, shape4d.data());
          ggml_set_name(t, brName.c_str());
          graph.weights.emplace(brName, t);
        };

    auto registerConvWithBias = [&](const std::string& convPrefix) {
      struct ggml_tensor* w = registerConvWeight(convPrefix + ".weight");
      addBiasBroadcast(convPrefix + ".bias", w->ne[3]);
    };

    registerConvWithBias("crnn.features.0.0");
    for (const BlockConfig& cfg : kBlocks) {
      const std::string base =
          "crnn.features." + std::to_string(cfg.featureIndex);
      const bool hasExpand = cfg.expansionChannels != cfg.inputChannels;
      int dwBlockIdx = 0;
      int seBlockIdx = -1;
      int projBlockIdx = 0;
      if (hasExpand) {
        registerConvWithBias(base + ".block.0.0");
        dwBlockIdx = 1;
        if (cfg.useSe) {
          seBlockIdx = 2;
          projBlockIdx = 3;
        } else {
          projBlockIdx = 2;
        }
      } else if (cfg.useSe) {
        seBlockIdx = 1;
        projBlockIdx = 2;
      } else {
        projBlockIdx = 1;
      }

      const std::string dwBase = base + ".block." + std::to_string(dwBlockIdx);
      registerConvWithBias(dwBase + ".0");
      if (cfg.useSe) {
        const std::string seBase =
            base + ".block." + std::to_string(seBlockIdx);
        registerConvWithBias(seBase + ".fc1");
        registerConvWithBias(seBase + ".fc2");
      }
      const std::string projBase =
          base + ".block." + std::to_string(projBlockIdx);
      registerConvWithBias(projBase + ".0");
    }
    registerConvWithBias("crnn.features.12.0");

    ggml_backend_buffer_type_t defaultCpuBuft =
        ggml_backend_get_default_buffer_type(graph.backend);
    ggml_backend_buffer_type_t prepackBuft = nullptr;
    {
      ggml_backend_buffer_type_t* extraBufts = nullptr;
      ggml_backend_dev_t cpuDev = ggml_backend_get_device(graph.backend);
      if (cpuDev != nullptr) {
        ggml_backend_reg_t cpuReg = ggml_backend_dev_backend_reg(cpuDev);
        if (cpuReg != nullptr) {
          auto* getExtras =
              reinterpret_cast<ggml_backend_dev_get_extra_bufts_t>(
                  ggml_backend_reg_get_proc_address(
                      cpuReg, "ggml_backend_dev_get_extra_bufts"));
          if (getExtras != nullptr) {
            extraBufts = getExtras(cpuDev);
          }
        }
      }
      if (extraBufts != nullptr) {
        const struct ggml_tensor* probe =
            ggml_get_tensor(ctx, "crnn.features.0.0.weight");
        if (probe != nullptr) {
          for (ggml_backend_buffer_type_t* p = extraBufts; *p != nullptr;
               ++p) {
            if (ggml_backend_buft_get_alloc_size(*p, probe) >
                ggml_nbytes(probe)) {
              prepackBuft = *p;
              break;
            }
          }
        }
      }
    }

    auto isPrepackable = [&](const std::string& name,
                             const struct ggml_tensor* t) {
      if (!name.ends_with(".weight")) {
        return false;
      }
      if (t->ne[2] == 1) {
        return false;
      }
      return true;
    };

    if (prepackBuft != nullptr) {
      for (auto& [name, dst] : graph.weights) {
        if (!isPrepackable(name, dst)) {
          continue;
        }
        const size_t allocSize =
            ggml_backend_buft_get_alloc_size(prepackBuft, dst);
        ggml_backend_buffer_t buf =
            ggml_backend_buft_alloc_buffer(prepackBuft, allocSize);
        if (buf == nullptr) {
          raise(
              "failed to allocate per-tensor prepack buffer for " + name);
        }
        ggml_tallocr tallocr = ggml_tallocr_new(buf);
        if (ggml_tallocr_alloc(&tallocr, dst) != GGML_STATUS_SUCCESS) {
          ggml_backend_buffer_free(buf);
          raise("ggml_tallocr_alloc failed for " + name);
        }
        ggml_backend_buffer_set_usage(buf, GGML_BACKEND_BUFFER_USAGE_WEIGHTS);
        graph.auxBuffers.push_back(buf);
      }
    }

    graph.weightsBuffer = ggml_backend_alloc_ctx_tensors_from_buft(
        graph.weightsCtx.get(), defaultCpuBuft);
    if (graph.weightsBuffer == nullptr) {
      raise("failed to allocate GGML weight buffer");
    }
    ggml_backend_buffer_set_usage(
        graph.weightsBuffer, GGML_BACKEND_BUFFER_USAGE_WEIGHTS);
    graph.extraBuffer = ggml_backend_alloc_ctx_tensors_from_buft(
        graph.extraCtx.get(), defaultCpuBuft);
    if (graph.extraBuffer == nullptr) {
      raise("failed to allocate GGML extra-tensor buffer");
    }
    ggml_backend_buffer_set_usage(
        graph.extraBuffer, GGML_BACKEND_BUFFER_USAGE_WEIGHTS);

    std::ifstream file(ggufPath, std::ios::binary);
    if (!file) {
      raise("failed to open GGUF file for raw read: " + ggufPath);
    }
    const size_t dataBaseOffset = gguf_get_data_offset(gguf);

    auto readBytes = [&](size_t fileOffset, size_t bytes) {
      std::vector<uint8_t> buf(bytes);
      file.seekg(static_cast<std::streamoff>(fileOffset));
      file.read(
          reinterpret_cast<char*>(buf.data()),
          static_cast<std::streamsize>(bytes));
      if (!file) {
        raise("file read failed while loading tensor data");
      }
      return buf;
    };
    auto readF16AsF32 = [&](size_t fileOffset, size_t count) {
      std::vector<ggml_fp16_t> raw(count);
      file.seekg(static_cast<std::streamoff>(fileOffset));
      file.read(
          reinterpret_cast<char*>(raw.data()),
          static_cast<std::streamsize>(count * sizeof(ggml_fp16_t)));
      if (!file) {
        raise("file read failed while loading F16 tensor data");
      }
      std::vector<float> out(count);
      fp16ToFp32(raw.data(), out.data(), count);
      return out;
    };

    for (auto& [name, dst] : graph.weights) {
      if (name.ends_with(".bias_br")) {
        // Synthesised bias_br: read source bias from GGUF, convert to F32.
        const std::string biasName =
            name.substr(0, name.size() - std::string("_br").size());
        const int64_t biasIdx = gguf_find_tensor(gguf, biasName.c_str());
        const size_t nElements = static_cast<size_t>(ggml_nelements(dst));
        std::vector<float> values(nElements, 0.0F);
        if (biasIdx >= 0) {
          const struct ggml_tensor* biasMeta =
              ggml_get_tensor(ctx, biasName.c_str());
          if (biasMeta != nullptr &&
              static_cast<size_t>(ggml_nelements(biasMeta)) == nElements) {
            const size_t off =
                dataBaseOffset + gguf_get_tensor_offset(gguf, biasIdx);
            if (biasMeta->type == GGML_TYPE_F16) {
              values = readF16AsF32(off, nElements);
            } else if (biasMeta->type == GGML_TYPE_F32) {
              std::vector<uint8_t> raw =
                  readBytes(off, nElements * sizeof(float));
              std::memcpy(
                  values.data(), raw.data(), nElements * sizeof(float));
            } else {
              raise(
                  "unsupported bias dtype " +
                  std::string(ggml_type_name(biasMeta->type)) + " for " +
                  biasName);
            }
          }
        }
        ggml_backend_tensor_set(
            dst, values.data(), 0, values.size() * sizeof(float));
        continue;
      }

      // Conv weight: same-dtype byte copy from the GGUF on-disk data.
      const int64_t idx = gguf_find_tensor(gguf, name.c_str());
      if (idx < 0) {
        raise("tensor missing from GGUF: " + name);
      }
      const size_t off = dataBaseOffset + gguf_get_tensor_offset(gguf, idx);
      const size_t bytes = ggml_nbytes(dst);
      std::vector<uint8_t> raw = readBytes(off, bytes);
      ggml_backend_tensor_set(dst, raw.data(), 0, bytes);
    }
  }

  void loadRecurrentWeights(
      gguf_context* gguf, const std::string& ggufPath) {
    struct ggml_context* ctx = graph.weightsCtx.get();
    std::ifstream file(ggufPath, std::ios::binary);
    if (!file) {
      raise("failed to open GGUF file for recurrent weights: " + ggufPath);
    }
    const size_t dataBaseOffset = gguf_get_data_offset(gguf);

    auto loadTensor = [&](const std::string& name) {
      const struct ggml_tensor* meta = ggml_get_tensor(ctx, name.c_str());
      if (meta == nullptr) {
        raise("missing tensor: " + name);
      }
      const int64_t idx = gguf_find_tensor(gguf, name.c_str());
      if (idx < 0) {
        raise("tensor missing from GGUF: " + name);
      }
      const size_t off = dataBaseOffset + gguf_get_tensor_offset(gguf, idx);
      const size_t count = ggml_nelements(meta);
      std::vector<float> out(count);
      if (meta->type == GGML_TYPE_F32) {
        file.seekg(static_cast<std::streamoff>(off));
        file.read(
            reinterpret_cast<char*>(out.data()),
            static_cast<std::streamsize>(count * sizeof(float)));
        if (!file) {
          raise("file read failed while loading " + name);
        }
      } else if (meta->type == GGML_TYPE_F16) {
        std::vector<ggml_fp16_t> raw(count);
        file.seekg(static_cast<std::streamoff>(off));
        file.read(
            reinterpret_cast<char*>(raw.data()),
            static_cast<std::streamsize>(count * sizeof(ggml_fp16_t)));
        if (!file) {
          raise("file read failed while loading " + name);
        }
        fp16ToFp32(raw.data(), out.data(), count);
      } else {
        raise(
            "unsupported tensor dtype for " + name + ": " +
            ggml_type_name(meta->type));
      }
      return out;
    };

    for (int layer = 0; layer < kLstmLayerCount; ++layer) {
      for (int direction = 0; direction < kLstmDirectionCount; ++direction) {
        const std::string suffix = direction == 0 ? "" : "_reverse";
        const std::string base = "crnn.decoder.";
        LstmWeights& dst =
            lstm[static_cast<size_t>(layer)][static_cast<size_t>(direction)];
        const std::string layerStr = std::to_string(layer);
        std::string weightIhPath = base;
        weightIhPath.append("weight_ih_l").append(layerStr).append(suffix);
        std::string weightHhPath = base;
        weightHhPath.append("weight_hh_l").append(layerStr).append(suffix);
        std::string biasIhPath = base;
        biasIhPath.append("bias_ih_l").append(layerStr).append(suffix);
        std::string biasHhPath = base;
        biasHhPath.append("bias_hh_l").append(layerStr).append(suffix);
        dst.weightIh = loadTensor(weightIhPath);
        dst.weightHh = loadTensor(weightHhPath);
        dst.biasIh = loadTensor(biasIhPath);
        dst.biasHh = loadTensor(biasHhPath);
        dst.inputSize = layer == 0 ? kFeatureChannels
                                   : kLstmHiddenSize * kLstmDirectionCount;
      }
    }
    linearWeight = loadTensor("crnn.linear.weight");
    linearBias = loadTensor("crnn.linear.bias");
  }

  void buildGraph() {
    graph.graphCtx = std::unique_ptr<struct ggml_context, decltype(&ggml_free)>(
        ggml_init(
            {.mem_size = (ggml_tensor_overhead() * kGraphCtxTensorOverhead) +
                         ggml_graph_overhead(),
             .mem_buffer = nullptr,
             .no_alloc = true}),
        ggml_free);
    if (!graph.graphCtx) {
      raise("failed to allocate GGML graph context");
    }

    struct ggml_context* ctx = graph.graphCtx.get();
    graph.input = ggml_new_tensor_4d(
        ctx, GGML_TYPE_F32, RECOG_WIDTH, RECOG_HEIGHT, kInputChannels, 1);
    ggml_set_name(graph.input, "recognition_input");
    ggml_set_input(graph.input);

    GraphBuilder gb{.ctx = ctx, .w = graph.weights};
    struct ggml_tensor* x = gb.convBnAct(
        graph.input,
        "crnn.features.0.0",
        2,
        2,
        3,
        true,
        true);
    for (const BlockConfig& cfg : kBlocks) {
      x = gb.invertedResidual(x, cfg);
    }
    x = gb.convBnAct(
        x, "crnn.features.12.0", 1, 1, 1, true, true);
    graph.features = x;
    ggml_set_name(graph.features, "crnn_features");
    ggml_set_output(graph.features);

    graph.graph = ggml_new_graph_custom(ctx, kMaxGraphNodes, /*grads=*/false);
    ggml_build_forward_expand(graph.graph, graph.features);

    graph.graphBuffer =
        ggml_backend_alloc_ctx_tensors(graph.graphCtx.get(), graph.backend);
    if (graph.graphBuffer == nullptr) {
      raise("failed to allocate GGML recognition graph buffer");
    }
  }
};

StepDoctrRecognitionGGML::StepDoctrRecognitionGGML(
    const std::string& pathRecognizer, int batchSize, DecodingMethod decoding)
    : impl_(std::make_unique<Impl>(pathRecognizer)), batchSize_(batchSize),
      decodingMethod_(decoding), vocabChars_(parseVocabToChars(VOCAB)) {
  const std::string decodingStr =
      (decoding == DecodingMethod::CTC) ? "CTC" : "ATTENTION";
  QLOG(
      qvac_lib_inference_addon_cpp::logger::Priority::INFO,
      "[DoctrRecognitionGGML] GGML CPU recognizer loaded, batchSize=" +
          std::to_string(batchSize) + ", decoding=" + decodingStr);
  ALOG_INFO(std::string(
      "[DoctrRecognitionGGML] GGML CPU recognizer loaded, decoding=" +
      decodingStr));
}

StepDoctrRecognitionGGML::~StepDoctrRecognitionGGML() = default;

cv::Mat StepDoctrRecognitionGGML::preprocessCrop(
    const cv::Mat& origImg, const std::array<cv::Point2f, 4>& polygon) {
  cv::Mat crop = fourPointTransform(origImg, polygon);
  if (crop.empty() || crop.cols == 0 || crop.rows == 0) {
    return cv::Mat::zeros(RECOG_HEIGHT, RECOG_WIDTH, CV_32FC3);
  }

  const int cropH = crop.rows;
  const int cropW = crop.cols;
  const float scaleH =
      static_cast<float>(RECOG_HEIGHT) / static_cast<float>(cropH);
  const float scaleW =
      static_cast<float>(RECOG_WIDTH) / static_cast<float>(cropW);
  const float cropScale = std::min(scaleH, scaleW);
  const int newH =
      std::max(1, static_cast<int>(static_cast<float>(cropH) * cropScale));
  const int newW =
      std::max(1, static_cast<int>(static_cast<float>(cropW) * cropScale));

  cv::Mat resized;
  cv::resize(crop, resized, cv::Size(newW, newH), 0, 0, cv::INTER_LINEAR);

  cv::Mat padded = cv::Mat::zeros(RECOG_HEIGHT, RECOG_WIDTH, resized.type());
  cv::Mat roi = padded(cv::Rect(0, 0, newW, newH));
  resized.copyTo(roi);

  cv::Mat floatImg;
  padded.convertTo(floatImg, CV_32FC3, 1.0 / kPixelMax);
  cv::subtract(floatImg, DOCTR_RECO_MEAN, floatImg);
  cv::divide(floatImg, DOCTR_RECO_STD, floatImg);
  return floatImg;
}

cv::Mat StepDoctrRecognitionGGML::runSingleInference(const cv::Mat& image) {
  CV_Assert(image.rows == RECOG_HEIGHT && image.cols == RECOG_WIDTH);
  CV_Assert(image.channels() == kInputChannels);
  const size_t planeFloats =
      static_cast<size_t>(RECOG_WIDTH) * RECOG_HEIGHT;
  inputBuffer_.assign(planeFloats * kInputChannels, 0.0F);

  std::vector<cv::Mat> channels;
  cv::split(image, channels);
  CV_Assert(static_cast<int>(channels.size()) == kInputChannels);
  for (int c = 0; c < kInputChannels; ++c) {
    CV_Assert(channels[c].isContinuous() && channels[c].type() == CV_32F);
    std::memcpy(
        inputBuffer_.data() + (planeFloats * static_cast<size_t>(c)),
        channels[c].ptr<float>(),
        planeFloats * sizeof(float));
  }

  std::vector<float> features = impl_->runFeatureExtractor(inputBuffer_);
  logitsBuffer_ = impl_->runLstmLinear(features);

  const std::array<int, 3> sizes = {1, kSequenceLength, kVocabSize};
  return cv::Mat(3, sizes.data(), CV_32F, logitsBuffer_.data()).clone();
}

StepDoctrRecognitionGGML::SoftmaxResult StepDoctrRecognitionGGML::softmaxArgmax(
    // NOLINTNEXTLINE(bugprone-easily-swappable-parameters)
    const cv::Mat& preds, int batchIdx, int timestep, int vocabSize) {
  const size_t batchStride = preds.step[0] / sizeof(float);
  const size_t seqStride = preds.step[1] / sizeof(float);
  const float* row =
      preds.ptr<float>() + (batchIdx * batchStride) + (timestep * seqStride);

  float maxVal = -std::numeric_limits<float>::infinity();
  for (int v = 0; v < vocabSize; v++) {
    maxVal = std::max(maxVal, row[v]);
  }

  float sumExp = 0.0F;
  int bestIdx = 0;
  float bestExp = 0.0F;
  for (int v = 0; v < vocabSize; v++) {
    const float expVal = std::exp(row[v] - maxVal);
    sumExp += expVal;
    if (expVal > bestExp) {
      bestExp = expVal;
      bestIdx = v;
    }
  }
  return {.bestIdx = bestIdx, .bestProb = bestExp / sumExp};
}

std::pair<std::string, float>
StepDoctrRecognitionGGML::decodeAttention(const cv::Mat& preds, int batchIdx) {
  const int seqLen = preds.size[1];
  const int vocabSize = preds.size[2];
  std::string decodedText;
  float confidenceSum = 0.0F;
  int numChars = 0;

  for (int t = 0; t < seqLen; t++) {
    auto [bestIdx, bestProb] = softmaxArgmax(preds, batchIdx, t, vocabSize);
    if (bestIdx >= SPECIAL_TOKEN_IDX) {
      break;
    }
    if (bestIdx >= 0 && std::cmp_less(bestIdx, vocabChars_.size())) {
      decodedText += vocabChars_[static_cast<size_t>(bestIdx)];
      confidenceSum += std::min(bestProb, 1.0F);
      numChars++;
    }
  }
  return {
      decodedText,
      numChars > 0 ? confidenceSum / static_cast<float>(numChars) : 0.0F};
}

std::pair<std::string, float>
StepDoctrRecognitionGGML::decodeCTC(const cv::Mat& preds, int batchIdx) {
  const int seqLen = preds.size[1];
  const int vocabSize = preds.size[2];
  std::string decodedText;
  float minConfidence = 1.0F;
  int prevIdx = -1;

  for (int t = 0; t < seqLen; t++) {
    auto [bestIdx, bestProb] = softmaxArgmax(preds, batchIdx, t, vocabSize);
    minConfidence = std::min(minConfidence, bestProb);
    if (bestIdx >= SPECIAL_TOKEN_IDX) {
      prevIdx = -1;
      continue;
    }
    if (bestIdx == prevIdx) {
      continue;
    }
    if (bestIdx >= 0 && std::cmp_less(bestIdx, vocabChars_.size())) {
      decodedText += vocabChars_[static_cast<size_t>(bestIdx)];
    }
    prevIdx = bestIdx;
  }
  return {decodedText, decodedText.empty() ? 0.0F : minConfidence};
}

StepDoctrRecognitionGGML::Output StepDoctrRecognitionGGML::process(
    Input input, const std::atomic<bool>* cancelFlag) {
  QLOG(
      qvac_lib_inference_addon_cpp::logger::Priority::DEBUG,
      "[DoctrRecognitionGGML] Processing " +
          std::to_string(input.polygons.size()) + " text regions");

  const cv::Mat& origImg = input.context.origImg;
  Output results;
  results.reserve(input.polygons.size());

  for (size_t batchStart = 0; batchStart < input.polygons.size();
       batchStart += static_cast<size_t>(batchSize_)) {
    if (cancelFlag != nullptr && cancelFlag->load(std::memory_order_relaxed)) {
      QLOG(
          qvac_lib_inference_addon_cpp::logger::Priority::INFO,
          "[DoctrRecognitionGGML] Cancelled at batch offset " +
              std::to_string(batchStart));
      break;
    }

    const size_t batchEnd = std::min(
        batchStart + static_cast<size_t>(batchSize_), input.polygons.size());
    for (size_t i = batchStart; i < batchEnd; ++i) {
      cv::Mat crop = preprocessCrop(origImg, input.polygons[i]);
      cv::Mat preds = runSingleInference(crop);
      auto [text, confidence] = (decodingMethod_ == DecodingMethod::CTC)
                                    ? decodeCTC(preds, 0)
                                    : decodeAttention(preds, 0);

      std::array<cv::Point2f, 4> polygon = input.polygons[i];
      if (input.context.initialResizeRatio != 1.0F) {
        const float scaleBack = 1.0F / input.context.initialResizeRatio;
        for (auto& pt : polygon) {
          pt.x *= scaleBack;
          pt.y *= scaleBack;
        }
      }
      results.emplace_back(polygon, text, confidence);
    }
  }

  QLOG(
      qvac_lib_inference_addon_cpp::logger::Priority::INFO,
      "[DoctrRecognitionGGML] Completed recognition of " +
          std::to_string(results.size()) + " regions");
  return results;
}

} // namespace doctr::ggml::pipeline

// NOLINTEND(cppcoreguidelines-pro-bounds-pointer-arithmetic,cppcoreguidelines-pro-bounds-constant-array-index,readability-identifier-naming,readability-identifier-length)
